name: CD
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build & inspect package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hynek/build-and-inspect-python-package@v2

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download built artifact to dist/
        uses: actions/download-artifact@v7
        with:
          name: Packages
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
